### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [jtoy/cld#14]
Dear @jtoy ,

we've recently added your CLD project to the incubator of our Ruby NLP list. Thank you a lot for your commitment!

You may want to be a part for the NLP network for Ruby developers. If so please consider adding the `rubynlp` topic to your repository.

You may also be interested in our other lists:
- https://github.com/arbox/nlp-with-ruby
- https://github.com/arbox/machine-learning-with-ruby

Thank you again!

**Comment by jtoy** [comment]
thanks @arbox
