### ISSUE TITLE
Release version with 3.2.0 compatibility

### ISSUE THREAD

**Issue by dkam** [jtoy/cld#24]
Hi there - any chance you could release a new version with the Ruby 3.2.0 compatibility updates?

**Comment by grosser** [comment]
need a PR to add that to CI and then fix all issues that pop up

**Comment by aka47** [comment]
The bug is actually fixed in the main branch here - https://github.com/jtoy/cld/commit/18787f5a139f9060fb2e2821a4b26f779f803180

It just needs a new release of the gem with the fix.
